name: build-release
on:
  push:
    tags:
      - 'v*'

env:
    GH_TOKEN: ${{ github.token }}

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Delete Release
      run: |
        gh release delete ${{ github.ref_name }} -y || true
    - name: Create Release
      run: |
        gh release create ${{ github.ref_name }} --title "Release ${{ github.ref_name }}" --notes "The version is ready. You can see the changed log: https://github.com/x-tools-author/wx-tools/blob/master/res/files/history.txt"
  release-for-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86, x64]
    needs: update-release
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build for Windows
      shell: cmd
      run: |
        git fetch --tags
        mkdir build
        cd build
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }}
        cmake -DWXT_MAKE_ZIP:BOOL=ON -DCMAKE_BUILD_TYPE=Release -DWXT_GENERATE_MSIX:BOOL=OFF -G "NMake Makefiles" ../
        cmake --build . --target wxTools
        dir && dir .\assets && dir .\assets\wxTools
    - name: Upload Release Asset for Windows
      run: |
        dir && gh release upload ${{ github.ref_name }} 'build\assets\wxtools-windows-${{ github.ref_name }}-${{ matrix.arch }}.zip'
