name: build-ubuntu
# on:
#   schedule:
#     - cron: '0 0 * * *'
on:
 push:
   branches:
     - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install-dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build automake libtool libgtk-3-dev pkg-config software-properties-common coreutils make pkg-config xvfb
      - name: build for linux
        run: |
          git fetch --tags
          cmake --version
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWXT_GENERATE_MSIX:BOOL=OFF -G "Ninja" ../
          cmake --build . --target all

