name: build-windows
# on:
#   schedule:
#     - cron: '0 0 * * *'
on:
 push:
   branches:
     - master
jobs:
  build-msvc:
    name: Build MSVC
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: build-msvc
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }}
          cmake -DCMAKE_BUILD_TYPE=Release -DWXT_GENERATE_MSIX:BOOL=OFF -G "NMake Makefiles" ../
          cmake --build . --target All
  build-minwg:
    name: Build MinGW
    strategy:
      matrix:
        # mingw 8.1, mingw 12.2, mingw 14.2
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: build-mingw
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DWXT_GENERATE_MSIX:BOOL=OFF -G "MinGW Makefiles" ../
          cmake --build . --target All
